# -*- coding: utf-8 -*-
"""2final20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzG8T7A_wBa2dtgkrrDmHIv5elQTEApW
"""

print("ดีงับสุดหล่อสุดสวย")
import random
print("เกมทายเลข")
number = random.randint(1,10)
guess = int(input("ทายเลขมาสื๊ (1-10): "))
if guess == number:
   print("ถูกต้องงง")
else:
  print("ผิดด")
  print("คำตอบที่ถูกคืออ",number)
  print("ทำโปรเเกรมโดย : (พัชรพล สองสี)")